version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  # frontend:
  #   image: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - .build:/var/www/html
  #   links:
  #     - backend

  # backend:
  #   image: python:3
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./outsight:/app
  #   links:
  #     - db
  #     - elasticsearch
