# Generated by Django 2.0.4 on 2018-04-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('address', models.TextField()),
                ('postal_code', models.IntegerField()),
                ('phone_number', models.CharField(max_length=255)),
                ('fax_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('vision_statement', models.TextField()),
                ('mission_statement', models.TextField()),
                ('philosophy', models.TextField(blank=True, null=True)),
                ('dgp_code', models.CharField(max_length=255)),
                ('zone_code', models.CharField(max_length=255)),
                ('cluster_code', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('main_level', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('offer', models.TextField()),
            ],
        ),
    ]
